- name: Check Installed Packages
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Display all installed packages
      ansible.builtin.debug:
        var: ansible_facts.packages
