- name: check value is greater than 10 or not #practicing conditions
  hosts: local
  connection: local
  vars: 
    value: 20
  tasks: 
  - name: check the value
    ansible.builtin.debug:
      msg: "given number is {{ value }} this,given value is greater than 10"
    when: value >= 10
  - name: check the value
    ansible.builtin.debug:
      msg: "given number is {{ value }} this,given value is less than 10"
    when: value <= 10