- name: check value is greater than 10 or not #practicing conditions
  hosts: local
  connection: local
  vars: 
    value: 5
  tasks: 
  - name: taking value from user
    prompt:
      prompt: "Enter the value"
      private: false
  - name: check the value
    ansible.builtin.debug:
      msg: "value is less than 10"
    when: value <= 10
  - name: check the value
    ansible.builtin.debug:
      msg: "value is greater than 10"
    when: value > 10