- name: check value is greater than 10 or not #practicing conditions
  hosts: local
  connection: local

  tasks: 
  - name: taking value from user
    pause:
      prompt: "Enter the value"
    register: input
  - name: check the value
    ansible.builtin.debug:
      msg: "value is less than 10"
    when: value <= 10
  - name: check the value
    ansible.builtin.debug:
      msg: "value is greater than 10"
    when: value > 10
