- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('lokesh') }}"

  - name: convert string to list
    vars:
      fruits: "banana,mango,apple" #string
    ansible.builtin.debug:
      msg: "Fruits are : {{ fruits.split(' , ') }}"


  - name: convert map into list
    vars: 
      course:
        name: ansible 
        duration: 10hrs
        learner: lokesh
    ansible.builtin.debug:
      msg: "courses are {{ course | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
    msg: "couse info : {{ course | items2dict }}"
    vars: 
      course:
      - {'key': 'name' , 'value': 'ansible'}
      - {'key': 'duration' , 'value': '10hrs'}
      - {'key': 'learner' , 'value': 'lokesh'}


  - name: upper to lower
    vars: 
      name: "lokesh"
    ansible.builtin.debug:
      msg: "hello : {{ name | lower }}"