- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - all_vars.yaml
  tasks:
    - name: "print course info"
      ansible.builtin.debug:
        msg: "course is {{ course }}, duratiuon is  {{ duration }}, Trainer is {{ Trainer }},learner is {{ learner }}"