- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: installing required packages
      ansible.builtin.packages:
        name: "{{ item }}"
        state: presnt
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "RedHat"
    - name: installing required packages
      ansible.builtin.packages:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "Debian"

