- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: installing required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "RHEL"
    - name: installing required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "Debian"