- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: installing required packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "RedHat""
    - name: installing required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - gcc
        - zip
        - mysql
      when: ansible_os_family == "Debian""
