- name: install packages
  hosts: web
  become: yes
  vars:
    packages:
      - git
      - gcc
      - zip
      - mysql
  tasks:
    - name: install required packages on RedHat
      ansible.builtin.packages:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: install required packages on Debian
      ansible.builtin.packages:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "Debian"
