- name: install packages
  hosts: web
  become: yes
     
  tasks:
    - name: install required packages on RedHat
      ansible.builtin.package:
        name: "item"
        state: installed
      loop:
      - git
      - gcc
      - zip
      - mysql
      when: ansible_os_family == "RedHat"

