- name: play1
  hosts: local
  connection: local #managing its own node no need oc credentials
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "hello from play1 and task1"


- name: play2
  hosts: local
  connection: local
  tasks:
    - name: play 2 and task1
      ansible.builtin.debug:
        msg: "hello from play2 and task1"