- name: install and run niginx
  hosts: web
  become: yes
  tasks:
  - name: install niginx
    ansible.builtin.package:
     name: niginx
     state: present
  - name: start niginx 
    ansible.builtin.service:
     name: niginx
     state: started
  