- name: installing niginx
  #hosts: aws_ec2
  hosts: web
  become: yes # -b "become is used to run the task as root user"
  serial: 3
  gather_facts: no
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  - name: run nginx
    tags: 
    - run
    ansible.builtin.service:
      name: nginx
      state: started
