- name: installing niginx
  hosts: ungrouped
  become: yes # -b "become is used to run the task as root user"
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
