- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
    - name: course
      prompt: "Enter course name"
      private: false
    - name: duration
      prompt: "Enter course duration"
      private: false
    - name: Trainer
      prompt: "Enter Trainer name"
      private: false
    - name: learner
      prompt: "Enter learner name"
      private: false
  tasks:
    - name: "print course info"
      ansible.builtin.debug:
        msg: "course is {{ course }}, duratiuon is  {{ duration }}, Trainer is {{ Trainer }},learner is {{ learner }}"
        