- name: shell vs command
  hosts: local
  connection: local
  tasks:  
    - name: execute ls commands
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
      #ansible.builtin.command: ls -ltr > /tmp/output.txt

    - name: executing ls command in command module
      #ansible.builtin.command: ls -ltr > /tmp/output.txt
      ansible.builtin.command: ls -ltr # it doesnt have redirections like shell so it will work here.
      register: command_result

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ command_result }}"                  
      