- name: variables
  hosts: local
  connection: local
  vars:
    course: devops
    duration: 120
    Trainer: "shivakumar"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ course }}, duratiuon is  {{ duration }}, Trainer is {{ Trainer }}"

