- name: variables
  hosts: local
  connection: local
  vars: # play level variables global variables
    greet: "hey hi im  from playbook"
  var_files:
  - all_vars.yaml
  vars_prompt:
  - name: "greet"
    prompt: "Enter the value"
    private: no
  tasks:
  - name: "print the variables"
    vars: 
      greet: "Task"
    ansible.builtin.debug:
      msg: "this is from {{ greet }}"