- name: variables from files
  hosts: web
    
  tasks:
    - name: "print course info"
      ansible.builtin.debug:
        msg: "course is {{ course }}, duratiuon is  {{ duration }}, Trainer is {{ Trainer }}"
        