- name: variables
  hosts: local
  connection: local
  vars: # play level variables global variables
    greet: "hey hi im from playbook"
  vars_files:
    - all_vars.yaml
  # vars_prompt:
  #   - name: greet
  #     prompt: Enter the value
  #     private: false
  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "this is from {{ greet }}"

#1st priority is command-line arguments
# 2nd priority is prompting the user to enter the value

# task level - inside tasks -> highest priority-------> its go to vars_files
#
